version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate  &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=adimotek.cl
      - DB_NAME=adimote3_eatools
      - DB_USER=adimote3_usuariodb
      - DB_PASS=M1C0ntr4s3n4!
