# Generated by Django 3.2.25 on 2025-11-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artefacts',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('subtype', models.CharField(blank=True, max_length=255)),
                ('alias', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('subcategory', models.CharField(blank=True, max_length=255)),
                ('version', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=255)),
                ('owner', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('objetive', models.CharField(blank=True, max_length=255)),
                ('range', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Diagrams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idart', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('diagram', models.TextField()),
            ],
        ),
    ]
