# Generated by Django 3.2.25 on 2025-11-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_artefacts_diagrams'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagrams',
            name='version',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
