# Generated by Django 3.2.25 on 2025-11-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_diagrams_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagrams',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
