# Generated by Django 3.2.25 on 2025-12-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_diagrams_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('users', models.IntegerField(default=0)),
                ('growth', models.FloatField(default=0.0)),
            ],
        ),
    ]
