# Generated by Django 3.2.25 on 2025-12-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_applications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='users',
            new_name='activeUsers',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='category',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='growth',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='icon',
        ),
        migrations.AddField(
            model_name='applications',
            name='developer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='applications',
            name='lastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='applications',
            name='version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='applications',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
