# Generated by Django 3.2.25 on 2025-12-09 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_artefact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='core.artefacts')),
                ('target_artefact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_links', to='core.artefacts')),
            ],
        ),
    ]
