# Generated by Django 3.2.25 on 2025-12-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tasklink'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='framework',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='applications',
            name='language',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='applications',
            name='os',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='applications',
            name='priority',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='applications',
            name='security',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='applications',
            name='type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
