# Generated by Django 3.2.25 on 2026-01-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20251210_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('arquitecto', 'Arquitecto'), ('colaborador', 'Colaborador')], default='colaborador', max_length=20),
        ),
    ]
